# Change these first
owner: alliancewebteam # Your GitHub organization or username, where this repository lives
repo: Website-Monitoring # The name of this repository
sites:
  - name: Alliance Computers
    url: https://alliancecomp.com
    
  - name: Access Bus & Van
    url: https://accessbusandvan.com
    
  - name: Allison Ong Shreffler, Architecture
    url: https://harrisburgarchitects.net
    
  - name: Allied Group PA
    url: https://alliedgrouppa.com
    
  - name: Allied Maintenance Systems
    url: https://alliedmaintenancesystems.com
    
  - name: AquaTek Cleaning Solutions
    url: https://aquatekpa.com
    
  - name: Anderson Pro Painting
    url: https://andersonpropainting.com
    
  - name: Autism York
    url: https://autismyork.org
    
  - name: A Plus Mortgage Solutions
    url: https://aplusmortgagesolutions.com
        
  - name: BHD - The Second Half
    url: https://bhdsecondhalf.com
    
  - name: Boone Graphics LLC
    url: https://boonegraphicsllc.com
    
  - name: Boyo Transportation
    url: https://boyotrans.com
    
  - name: Brentmore
    url: https://brentmore.net
    
  - name: Brewvino Hand-crafted Pizza
    url: https://brewvino.com
    
  - name: Bricks & Sticks Title Agency
    url: https://bns-settlements.com
    
  - name: Bucher Group
    url: https://buchergroup.com
    
  - name: Buckland Sales
    url: https://bucklandsales.com
        
  - name: Capital Hospitality Services
    url: https://chshotelrenovations.com
    
  - name: Carpet Care Solutions, Inc
    url: https://harrisburgarchitects.net
    
  - name: Castle Hill Resort & Spa
    url: https://www.castlehillresortvt.com
    
  - name: Center For Independent Living
    url: https://cilopportunities.org
    
  - name: Christ Presbyterian Church
    url: https://christchurchcamphill.org
    
  - name: Christopher Columbus Scholarship Foundation
    url: https://ccsfyorkpa.org
    
  - name: Christopher Columbus Scholarship Foundation - Scholarship Application
    url: https://forms.ccsfyorkpa.org
    
  - name: Clarke Benefits
    url: https://clarkebenefits4u.com
        
  - name: Creative Building Concepts
    url: https://buildsomethingcreative.com
        
  - name: DB360 Soft Wash
    url: https://db360wash.com
 
  - name: Dave Buell For PA House
    url: https://dbforpa.com
        
  - name: Down East Granite
    url: https://downeastfab.com
          
  - name: Dream Home Realty
    url: https://dreamhrpa.com
    
  - name: "Duffy's Bed And Biscuit"
    url: https://duffysbedandbiscuit.com
    
  - name: "ELI Consulting"
    url: https://educateinnovateinspire.com      
    
  - name: F&M Designs
    url: https://fandmdesigns.com
        
  - name: Fortney Printing
    url: https://fortneyprinting.com
            
  - name: GES America
    url: https://ges-america.com
            
  - name: Glossner & Mcelwee Family Dentistry
    url: https://gmdentalcare.net
            
  - name: Go Life Surfing Inc.
    url: https://golifesurfing.com
            
  - name: Guth Laboratories
    url: https://guthlabs.com
            
  - name: Habitat for Humanity of the Greater Harrisburg Area
    url: https://harrisburghabitat.org
            
  - name: Habitat for Humanity of the Greater Harrisburg Area - ReStore
    url: https://harrisburgrestore.org
            
  - name: Handyworx
    url: https://thehandyworx.com
    
  - name: "Henry's Lock & Key Service"
    url: https://thehandyworx.com
               
  - name: Hershey Real Estate Group
    url: https://hersheyreg.com

  - name: Hoem Inc. / Precision Metal Fabricating
    url: https:/precisionmetalpa.com
            
  - name: Home Builders Association of Metropolitan Harrisburg
    url: https://www.harrisburgbuilders.com
                          
  - name: HMR Auto Body
    url: https://hmrautobody.com
    
  - name: Impact Harrisburg
    url: https://impactharrisburg.org
                
  - name: Indian Creek
    url: https://indiancreekcommunity.org
                        
  - name: Jaz Design Co
    url: https://jazdesignco.com
    
  - name: JB Buy Rite
    url: https://jbbuyrite.com
    
  - name: John Jewett
    url: https://jhowardcahill.com
                
  - name: Key Painting
    url: https://keypainting.net
                    
  - name: "King's View Acres"
    url: https://kingsviewacres.com
                
  - name: Machining America
    url: https://machiningamerica.com
                    
  - name: Maria Memmi
    url: https://mariamemmi.com
    
   - name: Matterhorn Bar & Restaurant
    url: https://matterhornbar.com
    
   - name: Miller & Son Electro-Plating
    url: https://millerplatingnj.com
                
  - name: MJR Equipment
    url: https://mjrequipment.com
                
  - name: Moyles Muzic Law
    url: https://moyleslaw.com
                
  - name: Mr Sandman Flooring
    url: https://callmrsandman.com
    
  - name: Parker Surfcraft
    url: https://parkersurfcraft.com
    
  - name: Pigott Agency
    url: https://pigottagencyllc.com
                
  - name: PrimeFyre LLC
    url: https://primefyre.com
    
  - name: Reach For More
    url: https://reachformore.fit
        
  - name: "Redd's Smokehouse BBQ"
    url: https://reddssmokehousebbq.com
    
  - name: Ruthcliffe Lodge & Restaurant
    url: https://ruthcliffe.com    
                            
  - name: Saidis, Shultz, & Fisher
    url: https://www.ssfadvocates.com

  - name: "Savannah's"
    url: https://sohclub.com
                    
  - name: Securewire Technologies LLC
    url: https://securewiretech.com
    
  - name: Sees The Day, Inc.
    url: https://sees-the-day.com
                        
  - name: Seifert Woodcrafts
    url: https://seifertwc.com
    
  - name: "Shawn's Landscaping"
    url: https://shawns-landscaping.com
    
  - name: Simply Greek, Hershey
    url: https://simplygreekhershey.com
        
  - name: Stone and Edwards
    url: https://stoneandedwards.com
        
  - name: Strategic Response Firearms Training
    url: https://srft16.com/
    
  - name: Strube Inc.
    url: https://strubeinc.net
        
  - name: Sunrise Stables
    url: https://sunrisehorseboarding.com
         
  - name: "St. Paul's Evangelical Lutheran Church"
    url: https://stpaulsandhill.com
    
  - name: "Szeles and Associates"
    url: https://szelesas.com
        
  - name: "The Meadows Pet Resort"
    url: https://themeadowspetresort.com
        
  - name: "Tritan Pool and Spa"
    url: https://tritanpoolandspa.com
        
  - name: "Trix of the Trade Salon"
    url: https://trixofthetradesalon.com
        
  - name: "Unlimited Construction Services"
    url: https://ucs1.com
          
  - name: "Upon This Rock Ministries"
    url: https://uponthisrock2950.com
    
  - name: "V3 Fitness Pro"
    url: https://v3fitnesspro.com
      
  - name: "Wert Book Binding"
    url: https://wertbookbinding.com
    
  - name: "West Shire Decks"
    url: https://westshiredecks.com
    
  - name: "West Shore Elks"
    url: https://westshoreelks.org
            
  - name: "Wide Horizons Travel"
    url: https://widehorizonstravel.com
            
  - name: "Woodburn Law"
    url: https://woodburn-law.com
      
  - name: "Yorklyn Construction"
    url: https://yorklynconstruction.com
    
assignees: # Users to assign downtime issues (optional)
  - jonathansingel
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Website-Monitoring
  logoUrl: https://www.alliancecomp.com/wp-content/uploads/2021/04/ABT-logo-no-tag-300x116-1.png
  name: Website Status Monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://alliancewebteam.github.io/Website-Monitoring/). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
